services:

  # java - spring application
  crud-app:
    build: .
    container_name: crud-app-c
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres-db:5432/crud_api
      - DATABASE_USERNAME=berke
      - DATABASE_PASSWORD=pg-db-1234
    depends_on:
      - postgres-db

  # postgres database 
  postgres-db:
    image: postgres:12
    container_name: crud-db-c
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_USER=berke
      - POSTGRES_PASSWORD=pg-db-1234
      - POSTGRES_DB=crud_api
    volumes: 
      - pgdata:/var/lib/postgresql/data
 
  # postgres admin ui (pgadmin)
  postgres-admin: 
    image: dpage/pgadmin4
    container_name: crud-pg-c
    ports: 
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=sayinberke34@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pg-ui-1234

volumes:
  pgdata: {}